version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout
      - run
        name: Test
        command: make test


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
